image: python:3.6.4

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pytest classification_tool --cov=classification_tool
          - pytest evaluation_tool --cov=evaluation_tool
          - pytest loading_tool --cov=loading_tool
          - pytest utils --cov=utils
